In [1]:
import pandas as pd
import numpy as np

In [3]:
dataset = ["skoda", "pamap2_subject101", "pamap2_subject108", "motionsense_2", "motionsense_1", "mHealth_subject2", "mHealth_subject1"]
models = ["kmeans","gmmfull","gmmdiag","ticc","ticc0"]

In [4]:
def summarize(results):
    summarizes_name = []
    summarizes_mean = []
    summarizes_std = []
    epochs = int(results["w_model_epoch"].sort_values(ascending = False, ignore_index = True)[0].split("_")[-1]) + 1
    for i in range(0, len(results), epochs):
        summarizes_name.append(results.iloc[i,0])
        summarizes_mean.append(results[i:i+epochs].mean(axis=0).values.tolist())
        summarizes_std.append(results[i:i+epochs].std(axis=0).values.tolist())
    m = pd.DataFrame(summarizes_mean, columns = ["nmi","ami","ari","f1","acc"])
    s = pd.DataFrame(summarizes_std, columns = ["nmi","ami","ari","f1","acc"])
    r = pd.concat([m, s], axis = 1)
    r["w_model"] = summarizes_name
    return r

In [5]:
dataset = "skoda"
df = []
for i in range(1, 6):
    filename = "{:s}_TTC_{:d}.csv".format(dataset, i)
    df.append(pd.read_csv(filename).values[0])

In [72]:
np.array(df).std(axis = 0)

array([0.02168093, 0.02168512, 0.04120102, 0.07219825, 0.05399843])

In [73]:
df = pd.DataFrame(np.array(df), columns = ["nmi", "armi", "ari", "f1", "acc"])
df.to_csv("summarize_{:s}.csv".format(dataset), index = False)

In [74]:
df.std(axis = 0)

nmi     0.024240
armi    0.024245
ari     0.046064
f1      0.080720
acc     0.060372
dtype: float64

In [89]:
dataset = "pamap2"
df = []
for i in range(1, 6):
    filename = "{:s}_TTC_{:d}.csv".format(dataset, i)
    df.append(pd.read_csv(filename).values[0])

In [90]:
df

[array([0.79990889, 0.79981291, 0.70008787, 0.66274627, 0.72663619]),
 array([0.8104469 , 0.81035539, 0.70546087, 0.66546481, 0.74538511]),
 array([0.85263609, 0.85256547, 0.77198734, 0.71301788, 0.78758945]),
 array([0.74950973, 0.74938981, 0.57684737, 0.63134044, 0.66230735]),
 array([0.84319851, 0.84312304, 0.74590941, 0.68733291, 0.76407615])]

In [91]:
np.array(df).astype(float).mean(axis = 0)

array([0.81114002, 0.81104933, 0.70005857, 0.67198046, 0.73719885])

In [82]:
df = pd.DataFrame(np.array(df), columns = ["nmi", "armi", "ari", "f1", "acc"])
df.to_csv("summarize_{:s}.csv".format(dataset), index = False)

In [21]:
pd.read_csv("skoda_ablation_pseudoLabel.csv").iloc[12:].values.astype(float).mean(axis=0)

array([0.6097469 , 0.6096819 , 0.45038775, 0.56901768, 0.58439662])

In [23]:
pd.read_csv("skoda_ablation_pseudoLabel.csv").iloc[12:].values.astype(float).std(axis=0)

array([0.07165738, 0.07166958, 0.09493318, 0.08164354, 0.08419544])

In [21]:
import pandas as pd
import numpy as np

In [51]:
for dataset in ["mhealth",  "pamap2", "skoda"]:
    print(dataset)
    results = []
    for i in range(1,6):
        try:
            results.append(pd.read_csv("{:s}_TTC_noTCN5_{:d}.csv".format(dataset, i)))
        except:
            print(i)
            pass
    try:
        results = pd.concat(results, axis = 0)
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
    print(results.mean(axis = 0))
    print(results.std(axis = 0))

mhealth
2
nmi    0.745597
ami    0.745405
ari    0.560613
f1     0.581905
acc    0.642115
dtype: float64
nmi    0.103542
ami    0.103630
ari    0.140352
f1     0.106179
acc    0.095017
dtype: float64
pamap2
nmi    0.607383
ami    0.607185
ari    0.414146
f1     0.461380
acc    0.522412
dtype: float64
nmi    0.044856
ami    0.044879
ari    0.033194
f1     0.031616
acc    0.023627
dtype: float64
skoda
nmi    0.681396
ami    0.681358
ari    0.474523
f1     0.617856
acc    0.626141
dtype: float64
nmi    0.141107
ami    0.141126
ari    0.137534
f1     0.108328
acc    0.084353
dtype: float64


In [19]:
pd.read_csv("{:s}_TTC_noTCN_{:d}.csv".format("mhealth", 1)).iloc[-1,:].values

array(['0.9251614003831782', '0.9251091490858641', '0.8688983726257807',
       '0.8778992451078979', '0.8920225166316029'], dtype=object)

In [30]:
results.astype(float)

array([[0.9251614 , 0.92510915, 0.86889837, 0.87789925, 0.89202252],
       [0.9251614 , 0.92510915, 0.86889837, 0.87789925, 0.89202252],
       [0.9251614 , 0.92510915, 0.86889837, 0.87789925, 0.89202252],
       [0.9251614 , 0.92510915, 0.86889837, 0.87789925, 0.89202252],
       [0.9251614 , 0.92510915, 0.86889837, 0.87789925, 0.89202252]])

In [65]:
import pandas as pd
import numpy as np

In [67]:
for dataset in ["mhealth","pamap2", "skoda"]:
    print(dataset)
    results = []
    for i in range(1,6):
        try:
            results.append(pd.read_csv("{:s}_TTC_STCN2_{:d}.csv".format(dataset, i)).values[-1])
        except:
            print(i)
            pass
    try:
        results = pd.concat(results, axis = 0)
        print(results.mean(axis = 0))
        print(results.std(axis = 0))
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
        print(results.mean(axis = 0))
        print(results.std(axis = 0))
    except ValueError:
        print(dataset)

mhealth
1
2
3
4
5
mhealth
pamap2
[0.79829037 0.79819231 0.66445502 0.63966712 0.70518681]
[0.00498727 0.00498969 0.00573208 0.00567554 0.00332571]
skoda
1
2
3
4
5
skoda


In [64]:
for dataset in ["mhealth","pamap2", "skoda"]:
    print(dataset)
    results = []
    for i in range(1,6):
        try:
            results.append(pd.read_csv("{:s}_TTC_STCN3_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
        except:
            print(i)
            pass
    try:
        results = pd.concat(results, axis = 0)
        print(results.mean(axis = 0))
        print(results.std(axis = 0))
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
        print(results.mean(axis = 0))
        print(results.std(axis = 0))
    except ValueError:
        print(dataset)

mhealth
[0.94077326 0.94073164 0.89235771 0.87315414 0.90664696]
[0.00306664 0.00306871 0.00269912 0.02284695 0.00696633]
pamap2
1
2
3
4
5
pamap2
skoda
1
2
3
4
5
skoda


In [72]:
for dataset in ["skoda"]:
    print(dataset)
    results = []
    for i in range(1,6):
        try:
            results.append(pd.read_csv("{:s}_TTC_STCN5_0.3_0.0001_w128_attn_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
        except:
            print(i)
            pass
    try:
        results = pd.concat(results, axis = 0)
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
    print(results.mean(axis = 0))
    print(results.std(axis = 0))

skoda
[0.87964462 0.87963107 0.72409212 0.75557446 0.73647673]
[0.01786075 0.01786278 0.02973958 0.03766172 0.03037065]


In [109]:
for dataset in ["mhealth","pamap2", "skoda"]:
    print(dataset)
    results = []
    for i in range(1,6):
        try:
            results.append(pd.read_csv("{:s}_TTC_STCN5_0.3_0.0001_w1024_new_0.01_{:d}.csv".format(dataset, i)))
        except:
            print(i)
            pass
    try:
        results = pd.concat(results, axis = 0)
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
    print(results.mean(axis = 0))
    print(results.std(axis = 0))

mhealth
nmi    0.856344
ami    0.856243
ari    0.696646
f1     0.682375
acc    0.740513
dtype: float64
nmi    0.036497
ami    0.036523
ari    0.107540
f1     0.107721
acc    0.101030
dtype: float64
pamap2
5
nmi    0.824489
ami    0.824404
ari    0.700395
f1     0.664241
acc    0.741479
dtype: float64
nmi    0.009957
ami    0.009962
ari    0.020850
f1     0.012380
acc    0.011496
dtype: float64
skoda
1
2
3
4
5


ValueError: No objects to concatenate

In [120]:
for dataset in ["skoda"]:
    print(dataset)
    results = []
    for i in range(1,6):
        try:
            results.append(pd.read_csv("{:s}_TTC_STCN5_0.3_0.0001_w1024_0.01_{:d}.csv".format(dataset, i)).values[-1])
        except:
            print(i)
            pass
    try:
        results = pd.concat(results, axis = 0)
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
    print(results.mean(axis = 0))
    print(results.std(axis = 0)) 

skoda
[0.79313748 0.79311414 0.65866692 0.68208265 0.70516623]
[0.02432639 0.02432917 0.04822614 0.06095064 0.05984397]


In [111]:
for dataset in ["skoda"]:
    print(dataset)
    results = []
    for i in range(1,6):
        try:
            results.append(pd.read_csv("{:s}_TTC_STCN5_0.3_0.0001_w1024_new_0.01_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
        except:
            print(i)
            pass
    try:
        results = pd.concat(results, axis = 0)
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
    print(results.mean(axis = 0))
    print(results.std(axis = 0)) 

skoda
[0.73907589 0.73904633 0.58597574 0.63746903 0.66313976]
[0.05851962 0.05852644 0.07737389 0.07454951 0.06490047]


In [112]:
for dataset in ["mhealth"]:
    print(dataset)
    results = []
    for i in range(1,6):
        try:
            results.append(pd.read_csv("{:s}_TTC_STCN5_0.3_0.0001_w1024_new2_0.01_{:d}.csv".format(dataset, i)).values[-1])
            # results.append(pd.read_csv("{:s}_TTC_STCN5_0.3_0.0001_w1024_new_0.01_{:d}.csv".format(dataset, i)).values[-1])
        except:
            print(i)
            pass
    try:
        results = pd.concat(results, axis = 0)
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
    print(results)
    print(results.mean(axis = 0))
    print(results.std(axis = 0)) 

mhealth
[[0.90859532 0.90853145 0.85699967 0.88123423 0.90237107]
 [0.82790928 0.82778254 0.64766759 0.66804739 0.71640985]
 [0.90289037 0.90282224 0.85317857 0.89837907 0.91394212]
 [0.87194647 0.87185577 0.76580847 0.80627577 0.82833911]
 [0.81494649 0.81481177 0.66793188 0.63451306 0.68738273]]
[0.86525758 0.86516076 0.75831724 0.7776899  0.80968897]
[0.03811884 0.03814808 0.08855041 0.10828254 0.09323769]


In [115]:
for dataset in ["mhealth"]:
    print(dataset)
    results = []
    for i in range(1,6):
        try:
            results.append(pd.read_csv("{:s}_TTC_STCN5_0.3_0.0001_w1024_new_0.01_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
        except:
            print(i)
            pass
    try:
        results = pd.concat(results, axis = 0)
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
    print(results.mean(axis = 0))
    print(results.std(axis = 0))

mhealth
[0.87310134 0.87301042 0.77816044 0.77520542 0.82597373]
[0.02356319 0.0235801  0.05009462 0.05391615 0.0618786 ]


In [135]:
for dataset in ["pamap2"]:
    print(dataset)
    results = []
    for i in range(1,6):
        try:
            results.append(pd.read_csv("{:s}_TTC_STCN5_0.3_0.0001_w1024_new_0.01_{:d}.csv".format(dataset, i)).values[-1])
            results.append(pd.read_csv("{:s}_TTC_STCN5_0.3_0.0001_w1024_new_0.01_{:d}.csv".format(dataset, i)).values[-3])
        except:
            print(i)
            pass
    try:
        results = pd.concat(results, axis = 0)
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
    print(results)
    print(results.mean(axis = 0))
    print(results.std(axis = 0))

pamap2
4
5
[[0.78644479 0.78634147 0.65434506 0.64948182 0.71633586]
 [0.83010373 0.83002184 0.72312636 0.68235656 0.75678491]
 [0.8312062  0.83112429 0.70184356 0.6663659  0.74189379]
 [0.83278699 0.83270579 0.71005403 0.65877106 0.7403121 ]
 [0.83305812 0.83297711 0.71506365 0.67479155 0.76033409]
 [0.81045198 0.81036005 0.67499284 0.65462021 0.728893  ]
 [0.82461482 0.82452979 0.69340502 0.66121617 0.73992632]]
[0.82123809 0.82115148 0.69611865 0.66394332 0.74064001]
[0.01598825 0.01599595 0.02240534 0.01064254 0.01403764]


In [136]:
for dataset in ["pamap2"]:
    print(dataset)
    results = []
    for i in range(1,6):
        try:
            results.append(pd.read_csv("{:s}_TTC_STCN5_0.3_0.0001_w1024_new_0.01_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
        except:
            print(i)
            pass
    try:
        results = pd.concat(results, axis = 0)
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
    print(results)
    print(results.mean(axis = 0))
    print(results.std(axis = 0))

pamap2
4
5
[[0.80828884 0.80819567 0.68085738 0.68343527 0.75088247]
 [0.80105552 0.80095917 0.67051529 0.6393788  0.72111953]
 [0.84515295 0.84507791 0.7279265  0.66985684 0.75074745]]
[0.81816577 0.81807759 0.69309972 0.66422364 0.74091649]
[0.01930995 0.01931933 0.02498557 0.01842178 0.01399867]


In [143]:
for dataset in ["mhealth","pamap2", "skoda"]:
    print(dataset)
    results = []
    results_noPseudo = []
    for i in range(1,6):
        try:
            results.append(pd.read_csv("{:s}_TTC_MaxPool_w2048_{:d}.csv".format(dataset, i)).values[-1])
            results_noPseudo.append(pd.read_csv("{:s}_TTC_MaxPool_w2048_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
        except:
            print(i)
            pass
    try:
        results = pd.concat(results, axis = 0)
        results_noPseudo = pd.concat(results_noPseudo, axis = 0)
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
        results_noPseudo = np.stack(results_noPseudo, axis = 0)
        results_noPseudo = results_noPseudo.astype(float)
    print(results.mean(axis = 0))
    print(results.std(axis = 0))
    print(results_noPseudo.mean(axis = 0))
    print(results_noPseudo.std(axis = 0))

mhealth
[0.91879997 0.91874268 0.85267575 0.83847759 0.87420254]
[0.01690083 0.01691318 0.04243547 0.06814882 0.05162432]
[0.90671902 0.90665432 0.83091126 0.81650473 0.85692841]
[0.01750516 0.01751659 0.03761804 0.04016483 0.03147305]
pamap2
[0.83943302 0.83935536 0.72529224 0.67413207 0.75036938]
[0.01756663 0.01757557 0.03749678 0.02074573 0.01651784]
[0.82868477 0.82860199 0.7119853  0.66936568 0.7467932 ]
[0.01098888 0.01099427 0.02394993 0.01734459 0.01822397]
skoda
1
2
3
4
5


ValueError: No objects to concatenate

In [154]:
for dataset in ["mhealth","pamap2", "skoda"]:
    print(dataset)
    results = []
    results_noPseudo = []
    results_noICC = []
    for i in range(1,10):
        try:
            results.append(pd.read_csv("{:s}_TTC_MaxPool_w2048_{:d}.csv".format(dataset, i)).values[-1])
            # results_noPseudo.append(pd.read_csv("{:s}_TTC_MaxPool_w2048_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
            # results_noICC.append(pd.read_csv("{:s}_TTC_MaxPool_w2048_noICC_{:d}.csv".format(dataset, i)).values[-1])
        except FileNotFoundError:
            results.append(pd.read_csv("{:s}_TTC_maxpool_w2048_{:d}.csv".format(dataset, i)).values[-1])
            # results_noPseudo.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
            # results_noICC.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_noICC_{:d}.csv".format(dataset, i)).values[-1])
    try:
        results = pd.concat(results, axis = 0)
        # results_noPseudo = pd.concat(results_noPseudo, axis = 0)
        # results_noICC = pd.concat(results_noICC, axis = 0)
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
        # results_noPseudo = np.stack(results_noPseudo, axis = 0)
        # results_noPseudo = results_noPseudo.astype(float)
        # results_noICC = np.stack(results_noICC, axis = 0)
        # results_noICC = results_noICC.astype(float)
    print("Original")
    print(results)
    print(results.mean(axis = 0))
    print(results.std(axis = 0))
    # print("Original_noPseudo")
    # print(results_noPseudo)
    # print(results_noPseudo.mean(axis = 0))
    # print(results_noPseudo.std(axis = 0))
    # print("Original_noICC")
    # print(results_noICC)
    # print(results_noICC.mean(axis = 0))
    # print(results_noICC.std(axis = 0))

mhealth
Original
[[0.92862641 0.92857657 0.87994791 0.85122697 0.88940695]
 [0.94232103 0.94228066 0.90234782 0.93162345 0.93876159]
 [0.91464473 0.91458443 0.84052602 0.84952191 0.86308068]
 [0.89126107 0.89118352 0.77817161 0.71908489 0.78310684]
 [0.91714659 0.9170882  0.86238537 0.84093072 0.89665662]
 [0.93423176 0.93418518 0.87098178 0.8566957  0.88497185]
 [0.94505611 0.94501715 0.88687474 0.87326971 0.89520669]
 [0.91617367 0.91611458 0.8523612  0.83088069 0.88556889]
 [0.93263137 0.93258418 0.88814576 0.86078497 0.90464548]]
[0.92467697 0.92462383 0.8624158  0.84600211 0.8823784 ]
[0.01578701 0.01579838 0.03482165 0.0525034  0.03991222]
pamap2
Original
[[0.86484584 0.86478086 0.77687473 0.69598707 0.76924561]
 [0.82741192 0.82732802 0.68916365 0.64804577 0.72898945]
 [0.81673484 0.81664534 0.68000331 0.65265601 0.7368015 ]
 [0.85393769 0.85386753 0.75706    0.697039   0.76930347]
 [0.8342348  0.83415506 0.72335949 0.67693251 0.7475069 ]
 [0.82769866 0.82761495 0.69929506 0.639

In [176]:
for dataset in ["mhealth","pamap2", "skoda"]:
    print(dataset)
    results = []
    results_noPseudo = []
    results_noICC = []
    results_noICC_km = []
    for i in range(1,6):
        try:
            results.append(pd.read_csv("{:s}_TTC_MaxPool_w2048_saveResults_{:d}.csv".format(dataset, i)).values[-1])
            results_noPseudo.append(pd.read_csv("{:s}_TTC_MaxPool_w2048_saveResults_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
            # results_noICC.append(pd.read_csv("{:s}_TTC_MaxPool_w2048_saveResults_noICC_{:d}.csv".format(dataset, i)).values[-1])
            # results_noICC_km.append(pd.read_csv("{:s}_TTC_MaxPool_w2048_saveResults_km_noICC_{:d}.csv".format(dataset, i)).values[-1])
        # except FileNotFoundError:
        #     results.append(pd.read_csv("{:s}_TTC_maxpool_w2048_saveResults_{:d}.csv".format(dataset, i)).values[-1])
        #     results_noPseudo.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_saveResults_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
        #     # results_noICC.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_saveResults_noICC_{:d}.csv".format(dataset, i)).values[-1])
        #     # results_noICC_km.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_saveResults_km_noICC_{:d}.csv".format(dataset, i)).values[-1])
        except FileNotFoundError:
            results.append(pd.read_csv("{:s}_TTC_maxpool_w2048_p2_{:d}.csv".format(dataset, i)).values[-1])
            results_noPseudo.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_p2_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
            # results_noICC.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_saveResults_noICC_{:d}.csv".format(dataset, i)).values[-1])
            # results_noICC_km.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_saveResults_km_noICC_{:d}.csv".format(dataset, i)).values[-1])
        except FileNotFoundError:
            print(i)
            continue
    try:
        results = pd.concat(results, axis = 0)
        results_noPseudo = pd.concat(results_noPseudo, axis = 0)
        # results_noICC = pd.concat(results_noICC, axis = 0)
        # results_noICC_km = pd.concat(results_noICC_km, axis = 0)
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
        results_noPseudo = np.stack(results_noPseudo, axis = 0)
        results_noPseudo = results_noPseudo.astype(float)
        # results_noICC = np.stack(results_noICC, axis = 0)
        # results_noICC = results_noICC.astype(float)
        # results_noICC_km = np.stack(results_noICC_km, axis = 0)
        # results_noICC_km = results_noICC_km.astype(float)
    print("Original")
    print(results)
    print(results.mean(axis = 0))
    print(results.std(axis = 0))
    print("Original_noPseudo")
    print(results_noPseudo)
    print(results_noPseudo.mean(axis = 0))
    print(results_noPseudo.std(axis = 0))
    # print("Original_noICC")
    # # print(results_noICC)
    # print(results_noICC.mean(axis = 0))
    # print(results_noICC.std(axis = 0))
    # print("Original_noICC_km")
    # # print(results_noICC_km)
    # print(results_noICC_km.mean(axis = 0))
    # print(results_noICC_km.std(axis = 0))

mhealth


FileNotFoundError: [Errno 2] No such file or directory: 'mhealth_TTC_maxpool_w2048_p2_1.csv'

In [196]:
for dataset in ["skoda"]:
    print(dataset)
    results = []
    results_noPseudo = []
    results_noICC = []
    results_noICC_km = []
    for i in range(1,6):
        try:
            results.append(pd.read_csv("{:s}_TTC_MaxPool_w2048_saveResults_t2_b500_{:d}.csv".format(dataset, i)).values[-1])
            results_noPseudo.append(pd.read_csv("{:s}_TTC_MaxPool_w2048_saveResults_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
            # results_noICC.append(pd.read_csv("{:s}_TTC_MaxPool_w2048_saveResults_noICC_{:d}.csv".format(dataset, i)).values[-1])
            results_noICC_km.append(pd.read_csv("{:s}_TTC_MaxPool_w2048_saveResults_km_noICC_{:d}.csv".format(dataset, i)).values[-1])
        # except FileNotFoundError:
        #     results.append(pd.read_csv("{:s}_TTC_maxpool_w2048_saveResults_{:d}.csv".format(dataset, i)).values[-1])
        #     results_noPseudo.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_saveResults_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
        #     # results_noICC.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_saveResults_noICC_{:d}.csv".format(dataset, i)).values[-1])
            # results_noICC_km.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_saveResults_km_noICC_{:d}.csv".format(dataset, i)).values[-1])
        except FileNotFoundError:
            results.append(pd.read_csv("{:s}_TTC_maxpool_w2048_t2_b500_{:d}.csv".format(dataset, i)).values[-1])
            results_noPseudo.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
            # results_noICC.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_noICC_{:d}.csv".format(dataset, i)).values[-1])
            results_noICC_km.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_km_noICC_{:d}.csv".format(dataset, i)).values[-1])
        except FileNotFoundError:
            print(i)
            continue
    try:
        results = pd.concat(results, axis = 0)
        results_noPseudo = pd.concat(results_noPseudo, axis = 0)
        # results_noICC = pd.concat(results_noICC, axis = 0)
        results_noICC_km = pd.concat(results_noICC_km, axis = 0)
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
        results_noPseudo = np.stack(results_noPseudo, axis = 0)
        results_noPseudo = results_noPseudo.astype(float)
        # results_noICC = np.stack(results_noICC, axis = 0)
        # results_noICC = results_noICC.astype(float)
        results_noICC_km = np.stack(results_noICC_km, axis = 0)
        results_noICC_km = results_noICC_km.astype(float)
    print("Original")
    print(results)
    print(results.mean(axis = 0))
    print(results.std(axis = 0))
    print("NoPseudo")
    print(results_noPseudo)
    print(results_noPseudo.mean(axis = 0))
    print(results_noPseudo.std(axis = 0))
    print("NoICC")
    print(results_noICC_km)
    print(results_noICC_km.mean(axis = 0))
    print(results_noICC_km.std(axis = 0))

skoda
Original
[[0.86747552 0.86746033 0.80274428 0.79336299 0.83559207]
 [0.96281855 0.96281433 0.97235211 0.98370313 0.98542857]
 [0.88636362 0.88635058 0.83254716 0.80791301 0.85339645]
 [0.89640367 0.89639176 0.83944705 0.81324779 0.85925096]
 [0.87885628 0.87884236 0.814637   0.79852963 0.84499449]]
[0.89838353 0.89837187 0.85234552 0.83935131 0.87573251]
[0.03357645 0.03358031 0.06138753 0.07251006 0.05542535]
NoPseudo
[[0.87556054 0.87554641 0.78131885 0.80050808 0.82370705]
 [0.90044916 0.90043747 0.86669461 0.81460509 0.87882465]
 [0.77456377 0.77453769 0.59642276 0.64339432 0.68187418]
 [0.87628124 0.87626721 0.8171228  0.80598116 0.85564747]
 [0.89133819 0.8913257  0.83023083 0.80989898 0.85691656]]
[0.86363858 0.8636229  0.77835797 0.77487753 0.81939398]
[0.0455161  0.04552138 0.09498005 0.06590444 0.07097121]
NoICC
[[0.84333852 0.8433207  0.74150546 0.78305123 0.80984891]
 [0.9251771  0.9251686  0.93017544 0.96237626 0.9644561 ]
 [0.86452461 0.86450921 0.76617346 0.7902239

In [230]:
for dataset in ["mhealth", "pamap2","skoda"]:
    print(dataset)
    results = []
    results_noPseudo = []
    results_noICC = []
    results_noICC_km = []
    for i in range(1,6):
        if dataset != "pamap2":
            try:
                results.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_b100_3_{:d}.csv".format(dataset, i)).values[-1])
            except FileNotFoundError:
                results.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_b500_3_{:d}.csv".format(dataset, i)).values[-1])
            try:
                results_noPseudo.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_b100_3_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
            except FileNotFoundError:
                results_noPseudo.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_b500_3_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
            try:
                results_noICC.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_b100_3_gmm_noICC_{:d}.csv".format(dataset, i)).values[-1])
            except:
                results_noICC.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_b500_3_gmm_noICC_{:d}.csv".format(dataset, i)).values[-1])
            try:
                results_noICC_km.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_b100_3_km_noICC_{:d}.csv".format(dataset, i)).values[-1])
            except:
                results_noICC_km.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_b500_3_km_noICC_{:d}.csv".format(dataset, i)).values[-1])                
        else:
            try:
                results.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_3_b100_{:d}.csv".format(dataset, i)).values[-1])
                results_noPseudo.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_3_b100_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
                results_noICC.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_3_b100_gmm_noICC_{:d}.csv".format(dataset, i)).values[-1])
                results_noICC_km.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_3_b100_km_noICC_{:d}.csv".format(dataset, i)).values[-1])
            except FileNotFoundError:
                results.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_3_b500_{:d}.csv".format(dataset, i)).values[-1])
                results_noPseudo.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_3_b500_noPseudo_{:d}.csv".format(dataset, i)).values[-1])
                results_noICC.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_3_b500_gmm_noICC_{:d}.csv".format(dataset, i)).values[-1])
                results_noICC_km.append(pd.read_csv("{:s}_TTC_MaxPooling_w2048_3_b500_km_noICC_{:d}.csv".format(dataset, i)).values[-1])
            except FileNotFoundError:
                print(i)
                continue
    try:
        results = pd.concat(results, axis = 0)
        # results_noPseudo = pd.concat(results_noPseudo, axis = 0)
        # results_noICC = pd.concat(results_noICC, axis = 0)
        # results_noICC_km = pd.concat(results_noICC_km, axis = 0)
    except TypeError:
        results = np.stack(results, axis = 0)
        results = results.astype(float)
        results_noPseudo = np.stack(results_noPseudo, axis = 0)
        results_noPseudo = results_noPseudo.astype(float)
        results_noICC = np.stack(results_noICC, axis = 0)
        results_noICC = results_noICC.astype(float)
        results_noICC_km = np.stack(results_noICC_km, axis = 0)
        results_noICC_km = results_noICC_km.astype(float)
    print("Original")
    print(results)
    print(results.mean(axis = 0))
    print(results.std(axis = 0))
    print("Original_noPseudo")
    print(results_noPseudo)
    print(results_noPseudo.mean(axis = 0))
    print(results_noPseudo.std(axis = 0))
    print("Original_noICC")
    print(results_noICC)
    print(results_noICC.mean(axis = 0))
    print(results_noICC.std(axis = 0))
    print("Original_noICC_km")
    print(results_noICC_km)
    print(results_noICC_km.mean(axis = 0))
    print(results_noICC_km.std(axis = 0))

mhealth
Original
[[0.91381855 0.91375794 0.87318223 0.85638526 0.90598169]
 [0.90596137 0.90589491 0.83171687 0.83845373 0.89077159]
 [0.91081199 0.91074753 0.78530365 0.73674137 0.77474839]
 [0.92087085 0.92081483 0.82262306 0.80816545 0.83379769]
 [0.88195412 0.88187156 0.80674814 0.88427142 0.88451697]]
[0.90668338 0.90661736 0.82391479 0.82480345 0.85796327]
[0.01327628 0.01328526 0.02924153 0.05050135 0.04815796]
Original_noPseudo
[[0.89105377 0.89097647 0.79337731 0.8142974  0.83729459]
 [0.88605301 0.88597246 0.7844315  0.79800864 0.80784102]
 [0.93179104 0.93174344 0.89446611 0.91280542 0.92798658]
 [0.87766068 0.87757075 0.75127668 0.73455108 0.77770512]
 [0.896634   0.89656061 0.80697231 0.82307349 0.84488543]]
[0.8966385  0.89656474 0.80610478 0.81654721 0.83914255]
[0.01864994 0.01866407 0.04784625 0.05723695 0.05036666]
Original_noICC
[[0.84239505 0.84228085 0.64762998 0.71035305 0.7182578 ]
 [0.89029955 0.89022117 0.77499489 0.77219669 0.80087565]
 [0.89806721 0.89799471 

In [254]:
datast = "skoda"
for dataset in ["mhealth", "pamap2", "skoda"]:
    for model in ["", "noTCN_", "noPseudo_"]:
        results = []
        for i in range(1,6):
            results.append(pd.read_csv(f"{dataset}_TTC_MaxPooling_w2048_b100_n8_e2_0.3_{model}{i}.csv"))
        results = pd.concat(results)
        
        print(dataset, model)
        for m, s in zip(results.mean(axis=0), results.std(axis=0)):
            print("{:.3f} ( ± {:.3f} )".format(m,s))

mhealth 
0.917 ( ± 0.027 )
0.917 ( ± 0.027 )
0.868 ( ± 0.042 )
0.866 ( ± 0.048 )
0.908 ( ± 0.038 )
mhealth noTCN_
0.906 ( ± 0.013 )
0.905 ( ± 0.013 )
0.841 ( ± 0.021 )
0.855 ( ± 0.034 )
0.890 ( ± 0.024 )
mhealth noPseudo_
0.939 ( ± 0.021 )
0.938 ( ± 0.021 )
0.894 ( ± 0.048 )
0.866 ( ± 0.057 )
0.912 ( ± 0.050 )
pamap2 
0.813 ( ± 0.028 )
0.813 ( ± 0.028 )
0.698 ( ± 0.057 )
0.676 ( ± 0.054 )
0.731 ( ± 0.050 )
pamap2 noTCN_
0.811 ( ± 0.021 )
0.811 ( ± 0.021 )
0.704 ( ± 0.049 )
0.675 ( ± 0.027 )
0.742 ( ± 0.037 )
pamap2 noPseudo_
0.782 ( ± 0.012 )
0.782 ( ± 0.012 )
0.654 ( ± 0.032 )
0.646 ( ± 0.018 )
0.710 ( ± 0.033 )
skoda 
0.836 ( ± 0.045 )
0.836 ( ± 0.045 )
0.787 ( ± 0.057 )
0.777 ( ± 0.044 )
0.837 ( ± 0.041 )
skoda noTCN_
0.812 ( ± 0.044 )
0.812 ( ± 0.044 )
0.719 ( ± 0.114 )
0.761 ( ± 0.056 )
0.797 ( ± 0.080 )
skoda noPseudo_
0.861 ( ± 0.048 )
0.861 ( ± 0.048 )
0.820 ( ± 0.060 )
0.774 ( ± 0.085 )
0.849 ( ± 0.049 )


In [237]:
results

[array([[0.80078729, 0.80076397, 0.75917681, 0.75698249, 0.82083538]]),
 array([[0.80990302, 0.80988085, 0.7537402 , 0.76806981, 0.82689368]]),
 array([[0.90436081, 0.90434967, 0.87284253, 0.82269699, 0.88287278]]),
 array([[0.805553  , 0.8055302 , 0.73510683, 0.71860365, 0.78251244]]),
 array([[0.86005385, 0.86003751, 0.81618883, 0.81726768, 0.87071912]])]